export const practice = {
  Prolongation: [
    "Indviduals who have prolongation stuttering typically face issues with words with repeated consonants, words with long vowel sounds, multisyllabic words, complex consonant clusters, technical terms, words with abrupt transitions, and words with fricative or affricate sounds. Here are some speaking exercises to practice these skills.",
    "Get butter from the fridge and a bottle for the baby.",
    "See if you can go to the highest place.",
    "She was not on time to the party, but she still ate cake around the blue lake, wearing a coat to counteract the cold.",
    "Stopping procrastination is key to achieving success in the opportunities open to you.",
    "The strength of the twelfth person was unprecendented.",
    "The psychologist thwarted the villain's attempts to brainwash his patients.",
    "I optimized scalability and enhanced the system's resilience against latency issues.",
    "Quickly catch the ball and trap your opponent.",
    "You should choose to measure your suit for hemming.",
    "The people drank coffee as the laughed around the fire.",
  ],
  SoundRep: [
    "Individuals who have sound repetition stuttering repeat syllables of a word, making pronouncing words with multiple syllables difficult.",
    "The extravagant celebration filled the grand ballroom with laughter and merriment.",
    "Amidst the cacophony of bustling city streets, he found solace in tranquil parks.",
    "The majestic mountains towered over the picturesque landscape, casting long shadows at dusk.",
    "She embarked on a courageous journey to explore the uncharted territories of her imagination.",
    "The intricately woven tapestry depicted scenes of ancient mythology and folklore.",
  ],
  Interjection: [
    'Individuals who have interjection issues frequently use filler words. Practice the following sentences without using the indicated fillers such as "um" or "uh" or "you know."',
    "Um, well you see, the thing is um, a bit complex.",
    "Oh, well um, let me think about it about before I get back to you.",
    "Well, um, let's see, I guess, um, we could, like, go to the, uh, park and have a, you know, picnic or whatever.",
    "Hmm, well, I'm not, like, entirely sure, but, um, I think, uh, we're supposed to, you know, meet them at, uh, seven o'clock.",
    "So, um, yeah, I mean, I think we should, like, probably, you know, finish this, uh, project by, um, Friday, if that's okay with everyone?",
  ],
  WordRep: [
    "Individuals who have word repetition issues frequently repeat words. Practice the following sentences without repeating the words/phrases twice.",
    "I-I enjoy going for-walks in the park.",
    "Can you-you pass the salt, please-please?",
    "I need to-I need to finish this assignment before-before class.",
    "She-she likes to read-read books in her free time.",
    "Let's meet-let's meet at-at the coffee shop tomorrow.",
  ],
  Block: [
    "Individuals who have block stuttering frequently pause or gasp for air when forming sentences. Practice the following sentences by filling in the blanks without stopping once you begin talking.",
    "My favorite _____ is _______.",
    "Last week, the best thing that happened was ____ because ___.",
    "If I could _____, I would ____.",
    "I would love to learn ____ because ____.",
    "One thing I find ____ is ____.",
    "A ____ I think is ____ is ____.",
    "I feel most ____ when ____.",
  ],
};
